//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStoreAPI.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Price { get; set; }
        public Nullable<bool> InStock { get; set; }
        public Nullable<bool> Gameoftheweek { get; set; }
        public string ImageURL { get; set; }
        public string Imagethumbnail { get; set; }
        public string Shortdescription { get; set; }
        public string Longdescription { get; set; }
    }
}
